/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[13];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k_2x_1xx parms[0] 
 #define k_1xx_2x parms[1] 
 #define k_1x1xx_1xxx parms[2] 
 #define k_1xxx_1x1xx parms[3] 
 #define y0_0 parms[4] 
 #define y1_0 parms[5] 
 #define y2_0 parms[6] 
 #define y3_0 parms[7] 
 #define y4_0 parms[8] 
 #define y5_0 parms[9] 
 #define y6_0 parms[10] 
 #define y7_0 parms[11] 
 #define y8_0 parms[12] 
#define tmin range[0]
#define tmax range[1]


void odemodel_initmod(void (* odeparms)(int *, double *)) {
	 int N=13;
	 odeparms(&N, parms);
}

void odemodel_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -2.0*(k_2x_1xx*y[0]*y[0])+2.0*(k_1xx_2x*y[1])-1.0*(k_1x1xx_1xxx*y[1]*y[0])+1.0*(k_1xxx_1x1xx*y[2])-1.0*(k_2x_1xx*y[0]*y[3])+1.0*(k_1xx_2x*y[6])-1.0*(k_1x1xx_1xxx*y[0]*y[4])+1.0*(k_1xxx_1x1xx*y[8])-1.0*(k_1x1xx_1xxx*y[0]*y[6])+1.0*(k_1xxx_1x1xx*y[7]);
 	 ydot[1] = 1.0*(k_2x_1xx*y[0]*y[0])-1.0*(k_1xx_2x*y[1])-1.0*(k_1x1xx_1xxx*y[1]*y[0])+1.0*(k_1xxx_1x1xx*y[2])-1.0*(k_1x1xx_1xxx*y[1]*y[3])+1.0*(k_1xxx_1x1xx*y[7]);
 	 ydot[2] = 1.0*(k_1x1xx_1xxx*y[1]*y[0])-1.0*(k_1xxx_1x1xx*y[2]);
 	 ydot[3] = -2.0*(k_2x_1xx*y[3]*y[3])+2.0*(k_1xx_2x*y[4])-1.0*(k_1x1xx_1xxx*y[4]*y[3])+1.0*(k_1xxx_1x1xx*y[5])-1.0*(k_2x_1xx*y[0]*y[3])+1.0*(k_1xx_2x*y[6])-1.0*(k_1x1xx_1xxx*y[1]*y[3])+1.0*(k_1xxx_1x1xx*y[7])-1.0*(k_1x1xx_1xxx*y[6]*y[3])+1.0*(k_1xxx_1x1xx*y[8]);
 	 ydot[4] = 1.0*(k_2x_1xx*y[3]*y[3])-1.0*(k_1xx_2x*y[4])-1.0*(k_1x1xx_1xxx*y[4]*y[3])+1.0*(k_1xxx_1x1xx*y[5])-1.0*(k_1x1xx_1xxx*y[0]*y[4])+1.0*(k_1xxx_1x1xx*y[8]);
 	 ydot[5] = 1.0*(k_1x1xx_1xxx*y[4]*y[3])-1.0*(k_1xxx_1x1xx*y[5]);
 	 ydot[6] = 1.0*(k_2x_1xx*y[0]*y[3])-1.0*(k_1xx_2x*y[6])-1.0*(k_1x1xx_1xxx*y[6]*y[3])+1.0*(k_1xxx_1x1xx*y[8])-1.0*(k_1x1xx_1xxx*y[0]*y[6])+1.0*(k_1xxx_1x1xx*y[7]);
 	 ydot[7] = 1.0*(k_1x1xx_1xxx*y[1]*y[3])-1.0*(k_1xxx_1x1xx*y[7])+1.0*(k_1x1xx_1xxx*y[0]*y[6])-1.0*(k_1xxx_1x1xx*y[7]);
 	 ydot[8] = 1.0*(k_1x1xx_1xxx*y[0]*y[4])-1.0*(k_1xxx_1x1xx*y[8])+1.0*(k_1x1xx_1xxx*y[6]*y[3])-1.0*(k_1xxx_1x1xx*y[8]);

}

