/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[28];
static double forc[0];
static double cons[0];
static double eventcounter[1];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k_2a_1aa parms[0] 
 #define k_1aa_2a parms[1] 
 #define k_1a1aa_1aaa parms[2] 
 #define k_1aaa_1a1aa parms[3] 
 #define k_1a1b_1ab parms[4] 
 #define k_1ab_1a1b parms[5] 
 #define k_1a1bb_1abb parms[6] 
 #define k_1abb_1a1bb parms[7] 
 #define k_1a1ab_1aab parms[8] 
 #define k_1aab_1a1ab parms[9] 
 #define k_1aa1b_1aab parms[10] 
 #define k_1aab_1aa1b parms[11] 
 #define k_2b_1bb parms[12] 
 #define k_1bb_2b parms[13] 
 #define k_1b1bb_1bbb parms[14] 
 #define k_1bbb_1b1bb parms[15] 
 #define k_1ab1b_1abb parms[16] 
 #define k_1abb_1ab1b parms[17] 
 #define y0_0 parms[18] 
 #define y1_0 parms[19] 
 #define y2_0 parms[20] 
 #define y3_0 parms[21] 
 #define y4_0 parms[22] 
 #define y5_0 parms[23] 
 #define y6_0 parms[24] 
 #define y7_0 parms[25] 
 #define y8_0 parms[26] 
 #define y9_0 parms[27] 
#define tmin range[0]
#define tmax range[1]


void x_Pex14_initmod(void (* odeparms)(int *, double *)) {
	 int N=28;
	 odeparms(&N, parms);
	 for(int i=0; i<1; ++i) eventcounter[i] = 0;
}

void x_Pex14_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void x_Pex14_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -2.0*(k_2a_1aa*y[0]*y[0])+2.0*(k_1aa_2a*y[1])-1.0*(k_1a1aa_1aaa*y[1]*y[0])+1.0*(k_1aaa_1a1aa*y[2])-1.0*(k_1a1b_1ab*y[0]*y[3]*y[9])+1.0*(k_1ab_1a1b*y[6]*y[9])-1.0*(k_1a1bb_1abb*y[0]*y[4]*y[9])+1.0*(k_1abb_1a1bb*y[8]*y[9])-1.0*(k_1a1ab_1aab*y[0]*y[6]*y[9])+1.0*(k_1aab_1a1ab*y[7]*y[9]);
 	 ydot[1] = 1.0*(k_2a_1aa*y[0]*y[0])-1.0*(k_1aa_2a*y[1])-1.0*(k_1a1aa_1aaa*y[1]*y[0])+1.0*(k_1aaa_1a1aa*y[2])-1.0*(k_1aa1b_1aab*y[1]*y[3]*y[9])+1.0*(k_1aab_1aa1b*y[7]*y[9]);
 	 ydot[2] = 1.0*(k_1a1aa_1aaa*y[1]*y[0])-1.0*(k_1aaa_1a1aa*y[2]);
 	 ydot[3] = -2.0*(k_2b_1bb*y[3]*y[3])+2.0*(k_1bb_2b*y[4])-1.0*(k_1b1bb_1bbb*y[4]*y[3])+1.0*(k_1bbb_1b1bb*y[5])-1.0*(k_1a1b_1ab*y[0]*y[3]*y[9])+1.0*(k_1ab_1a1b*y[6]*y[9])-1.0*(k_1aa1b_1aab*y[1]*y[3]*y[9])+1.0*(k_1aab_1aa1b*y[7]*y[9])-1.0*(k_1ab1b_1abb*y[6]*y[3]*y[9])+1.0*(k_1abb_1ab1b*y[8]*y[9]);
 	 ydot[4] = 1.0*(k_2b_1bb*y[3]*y[3])-1.0*(k_1bb_2b*y[4])-1.0*(k_1b1bb_1bbb*y[4]*y[3])+1.0*(k_1bbb_1b1bb*y[5])-1.0*(k_1a1bb_1abb*y[0]*y[4]*y[9])+1.0*(k_1abb_1a1bb*y[8]*y[9]);
 	 ydot[5] = 1.0*(k_1b1bb_1bbb*y[4]*y[3])-1.0*(k_1bbb_1b1bb*y[5]);
 	 ydot[6] = 1.0*(k_1a1b_1ab*y[0]*y[3]*y[9])-1.0*(k_1ab_1a1b*y[6]*y[9])-1.0*(k_1ab1b_1abb*y[6]*y[3]*y[9])+1.0*(k_1abb_1ab1b*y[8]*y[9])-1.0*(k_1a1ab_1aab*y[0]*y[6]*y[9])+1.0*(k_1aab_1a1ab*y[7]*y[9]);
 	 ydot[7] = 1.0*(k_1aa1b_1aab*y[1]*y[3]*y[9])-1.0*(k_1aab_1aa1b*y[7]*y[9])+1.0*(k_1a1ab_1aab*y[0]*y[6]*y[9])-1.0*(k_1aab_1a1ab*y[7]*y[9]);
 	 ydot[8] = 1.0*(k_1a1bb_1abb*y[0]*y[4]*y[9])-1.0*(k_1abb_1a1bb*y[8]*y[9])+1.0*(k_1ab1b_1abb*y[6]*y[3]*y[9])-1.0*(k_1abb_1ab1b*y[8]*y[9]);
 	 ydot[9] = -1.0*(0.0);

}

/** Event function **/
void x_Pex14_myevent(int *n, double *t, double *y) {

	 double time = *t;

	 if(*t == 70.0 & eventcounter[0] == 0) {
		y[9] = 1.0;
		eventcounter[0] = eventcounter[0] + 1.;
	 }


}
